#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  block compile yarn

  mkdir -p "$shome/bin"
  ln -nfs $(yarn exec -s which nexe) "$shome/bin/"
  ln -nfs $(yarn exec -s which pkg) "$shome/bin/npkg"
}

main "$@"
