#!/usr/bin/env bash

function _node_exe_profile {
  local shome="${_node_exe_home:="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"

  export PKG_CACHE_PATH="${DATA}/cache/npkg"
}

_node_exe_profile
